version: '3.4'

services:
  interview.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  recruiting.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  onboarding.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apigatewaylayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  authentication.apilayer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

